static const char ms_stdlib_l[] =
"; Machdyne Scheme Standard Library\n"
";\n"
"; Notes on this revision:\n"
";   - `and`, `or`, `if`, `cond`, `case`, `let`, `let*`, `letrec`, `do`,\n"
";     `define`, `defun`, `lambda`, `begin`, `set!`, `while`, `quote`,\n"
";     `quasiquote`, `delay` are core special forms built into the\n"
";     interpreter (see ms.c) and are NOT defined here.\n"
";   - Only #f is false; '() (the empty list) is a TRUE value, matching\n"
";     R4RS/R5RS and unlike some earlier revisions of this Lisp.\n"
";   - A large set of R4RS procedures (numeric predicates/ops, char and\n"
";     string procedures, vector procedures, eq?/eqv?/equal?, memq/assq\n"
";     family, apply, force, call/cc, dynamic-wind, ...) are built into\n"
";     the interpreter directly -- see README.md for the full list. Only\n"
";     what's naturally expressed in Lisp itself lives here.\n"
";   - Everything below is ordinary user-level Lisp, so it is easy to trim\n"
";     for very small deployments: just drop the definitions you don't need.\n"
"\n"
"; --- caar/cadr family (through 4 levels, per R4RS) ----------------------\n"
"\n"
"(define (caar x) (car (car x)))\n"
"(define (cadr x) (car (cdr x)))\n"
"(define (cdar x) (cdr (car x)))\n"
"(define (cddr x) (cdr (cdr x)))\n"
"(define (caaar x) (car (caar x)))\n"
"(define (caadr x) (car (cadr x)))\n"
"(define (cadar x) (car (cdar x)))\n"
"(define (caddr x) (car (cddr x)))\n"
"(define (cdaar x) (cdr (caar x)))\n"
"(define (cdadr x) (cdr (cadr x)))\n"
"(define (cddar x) (cdr (cdar x)))\n"
"(define (cdddr x) (cdr (cddr x)))\n"
"(define (caaaar x) (car (caaar x)))\n"
"(define (caaadr x) (car (caadr x)))\n"
"(define (caadar x) (car (cadar x)))\n"
"(define (caaddr x) (car (caddr x)))\n"
"(define (cadaar x) (car (cdaar x)))\n"
"(define (cadadr x) (car (cdadr x)))\n"
"(define (caddar x) (car (cddar x)))\n"
"(define (cadddr x) (car (cdddr x)))\n"
"(define (cdaaar x) (cdr (caaar x)))\n"
"(define (cdaadr x) (cdr (caadr x)))\n"
"(define (cdadar x) (cdr (cadar x)))\n"
"(define (cdaddr x) (cdr (caddr x)))\n"
"(define (cddaar x) (cdr (cdaar x)))\n"
"(define (cddadr x) (cdr (cdadr x)))\n"
"(define (cdddar x) (cdr (cddar x)))\n"
"(define (cddddr x) (cdr (cdddr x)))\n"
"\n"
"; --- basic predicates ----------------------------------------------------\n"
"\n"
"(define (nil? x) (eq? x '()))\n"
"(define null nil?)\n"
"(define (list? x) (or (nil? x) (pair? x)))\n"
"\n"
"(define first car)\n"
"(define rest cdr)\n"
"(define second cadr)\n"
"(define third caddr)\n"
"\n"
"; --- list construction / traversal --------------------------------------\n"
"\n"
"(define (append . lists)\n"
"  (if (nil? lists)\n"
"      '()\n"
"      (if (nil? (cdr lists))\n"
"          (car lists)\n"
"          (append2 (car lists) (apply append (cdr lists))))))\n"
"\n"
"(define (append2 x y)\n"
"  (if (nil? x) y (cons (car x) (append2 (cdr x) y))))\n"
"\n"
"(define (reverse l)\n"
"  (define (rev l acc)\n"
"    (if (nil? l) acc (rev (cdr l) (cons (car l) acc))))\n"
"  (rev l '()))\n"
"\n"
"(define (list-tail l k)\n"
"  (if (= k 0) l (list-tail (cdr l) (- k 1))))\n"
"\n"
"(define (list-ref l i) (car (list-tail l i)))\n"
"\n"
"(define (last-pair l) (if (nil? (cdr l)) l (last-pair (cdr l))))\n"
"(define (last l) (car (last-pair l)))\n"
"\n"
"; single-list map/for-each (used to build the variadic versions below,\n"
"; and useful directly when you only have one list anyway)\n"
"(define (map1 f l)\n"
"  (if (nil? l) '() (cons (f (car l)) (map1 f (cdr l)))))\n"
"(define (for-each1 f l)\n"
"  (if (nil? l) '() (begin (f (car l)) (for-each1 f (cdr l)))))\n"
"\n"
"(define (any-nil? lists)\n"
"  (cond ((nil? lists) #f)\n"
"        ((nil? (car lists)) #t)\n"
"        (else (any-nil? (cdr lists)))))\n"
"\n"
"; (map f list1 list2 ...) -- R4RS map accepts any number of lists,\n"
"; stepping through them in parallel and stopping at the shortest.\n"
"(define (map f . lists)\n"
"  (if (any-nil? lists)\n"
"      '()\n"
"      (cons (apply f (map1 car lists))\n"
"            (apply map f (map1 cdr lists)))))\n"
"\n"
"(define (for-each f . lists)\n"
"  (if (any-nil? lists)\n"
"      #f\n"
"      (begin (apply f (map1 car lists))\n"
"             (apply for-each f (map1 cdr lists)))))\n"
"\n"
"(define (reduce f a l)\n"
"  (if (nil? l) a (reduce f (f a (car l)) (cdr l))))\n"
"\n"
"(define (filter pred l)\n"
"  (cond ((nil? l) '())\n"
"        ((pred (car l)) (cons (car l) (filter pred (cdr l))))\n"
"        (else (filter pred (cdr l)))))\n"
"\n"
"(define (remove pred l)\n"
"  (filter (lambda (x) (not (pred x))) l))\n"
"\n"
"; member?/count are extensions (not R4RS); member/assoc below are R4RS\n"
"; and, per spec, return #f (not '()) when nothing matches.\n"
"(define (member? x l)\n"
"  (cond ((nil? l) #f)\n"
"        ((equal? (car l) x) #t)\n"
"        (else (member? x (cdr l)))))\n"
"\n"
"(define (member x l)\n"
"  (cond ((nil? l) #f)\n"
"        ((equal? (car l) x) l)\n"
"        (else (member x (cdr l)))))\n"
"\n"
"(define (assoc x l)\n"
"  (cond ((nil? l) #f)\n"
"        ((equal? (caar l) x) (car l))\n"
"        (else (assoc x (cdr l)))))\n"
"\n"
"(define (count x l)\n"
"  (cond ((nil? l) 0)\n"
"        ((equal? (car l) x) (+ 1 (count x (cdr l))))\n"
"        (else (count x (cdr l)))))\n"
"\n"
"(define (flatten x)\n"
"  (cond ((nil? x) '())\n"
"        ((not (pair? x)) (list x))\n"
"        (else (append (flatten (car x)) (flatten (cdr x))))))\n"
"\n"
"(define (range a b)\n"
"  (if (>= a b) '() (cons a (range (+ a 1) b))))\n"
"\n"
"; --- sorting --------------------------------------------------------------\n"
"\n"
"(define (sort l)\n"
"  (if (or (nil? l) (nil? (cdr l)))\n"
"      l\n"
"      (let ((pivot (car l)) (tail (cdr l)))\n"
"        (append\n"
"          (sort (filter (lambda (x) (<= x pivot)) tail))\n"
"          (list pivot)\n"
"          (sort (filter (lambda (x) (> x pivot)) tail))))))\n"
"\n"
"; --- misc -------------------------------------------------------------\n"
"\n"
"(define (square x) (* x x))\n"
"(define (identity x) x)\n"
"(define (1+ x) (+ x 1))\n"
"(define (1- x) (- x 1))\n"
"";
